config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :sleeps
  resources :steps
  resources :med_coverages
  resources :prescriptions
  resources :visits
  resources :users

  get    '/login',  to: 'sessions#new',     as: 'new_login'
  post   '/login',  to: 'sessions#create',  as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  root 'homepage#index'

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :user
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @prescriptions = Prescription.all
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:name, :dosage, :frequency, :brand, :date_prescribed, :refill_till, :rx_notes, :user_id)
    end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= form_for(@prescription) do |f| %>
  <% if @prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% @prescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dosage %><br>
    <%= f.number_field :dosage %>
  </div>
  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.text_field :frequency %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.check_box :brand %>
  </div>
  <div class="field">
    <%= f.label :date_prescribed %><br>
    <%= f.date_select :date_prescribed %>
  </div>
  <div class="field">
    <%= f.label :refill_till %><br>
    <%= f.date_select :refill_till %>
  </div>
  <div class="field">
    <%= f.label :rx_notes %><br>
    <%= f.text_field :rx_notes %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing Prescription</h1>

<%= render 'form' %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prescriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dosage</th>
      <th>Frequency</th>
      <th>Brand</th>
      <th>Date prescribed</th>
      <th>Refill till</th>
      <th>Rx notes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td><%= prescription.name %></td>
        <td><%= prescription.dosage %></td>
        <td><%= prescription.frequency %></td>
        <td><%= prescription.brand %></td>
        <td><%= prescription.date_prescribed %></td>
        <td><%= prescription.refill_till %></td>
        <td><%= prescription.rx_notes %></td>
        <td><%= prescription.user %></td>
        <td><%= link_to 'Show', prescription %></td>
        <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
        <td><%= link_to 'Destroy', prescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New Prescription</h1>

<%= render 'form' %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prescription.name %>
</p>

<p>
  <strong>Dosage:</strong>
  <%= @prescription.dosage %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @prescription.frequency %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @prescription.brand %>
</p>

<p>
  <strong>Date prescribed:</strong>
  <%= @prescription.date_prescribed %>
</p>

<p>
  <strong>Refill till:</strong>
  <%= @prescription.refill_till %>
</p>

<p>
  <strong>Rx notes:</strong>
  <%= @prescription.rx_notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @prescription.user %>
</p>

<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>