config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :sleeps
  resources :steps
  resources :med_coverages
  resources :prescriptions
  resources :visits
  resources :users

  get    '/login',  to: 'sessions#new',     as: 'new_login'
  post   '/login',  to: 'sessions#create',  as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  root 'homepage#index'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :user
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:physician_first, :physician_last, :dos, :reason_for_visit, :diagnosis, :dr_notes, :user_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :physician_first %><br>
    <%= f.text_field :physician_first %>
  </div>
  <div class="field">
    <%= f.label :physician_last %><br>
    <%= f.text_field :physician_last %>
  </div>
  <div class="field">
    <%= f.label :dos %><br>
    <%= f.date_select :dos %>
  </div>
  <div class="field">
    <%= f.label :reason_for_visit %><br>
    <%= f.text_field :reason_for_visit %>
  </div>
  <div class="field">
    <%= f.label :diagnosis %><br>
    <%= f.text_field :diagnosis %>
  </div>
  <div class="field">
    <%= f.label :dr_notes %><br>
    <%= f.text_field :dr_notes %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visits</h1>

<table>
  <thead>
    <tr>
      <th>Physician first</th>
      <th>Physician last</th>
      <th>Dos</th>
      <th>Reason for visit</th>
      <th>Diagnosis</th>
      <th>Dr notes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.physician_first %></td>
        <td><%= visit.physician_last %></td>
        <td><%= visit.dos %></td>
        <td><%= visit.reason_for_visit %></td>
        <td><%= visit.diagnosis %></td>
        <td><%= visit.dr_notes %></td>
        <td><%= visit.user %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician first:</strong>
  <%= @visit.physician_first %>
</p>

<p>
  <strong>Physician last:</strong>
  <%= @visit.physician_last %>
</p>

<p>
  <strong>Dos:</strong>
  <%= @visit.dos %>
</p>

<p>
  <strong>Reason for visit:</strong>
  <%= @visit.reason_for_visit %>
</p>

<p>
  <strong>Diagnosis:</strong>
  <%= @visit.diagnosis %>
</p>

<p>
  <strong>Dr notes:</strong>
  <%= @visit.dr_notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @visit.user %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>