config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :sleeps
  resources :steps
  resources :med_coverages
  resources :prescriptions
  resources :visits
  resources :users

  get    '/login',  to: 'sessions#new',     as: 'new_login'
  post   '/login',  to: 'sessions#create',  as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  root 'homepage#index'

end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
  belongs_to :user
end

app/controllers/sleeps_controller.rb
class SleepsController < ApplicationController
  before_action :set_sleep, only: [:show, :edit, :update, :destroy]

  # GET /sleeps
  # GET /sleeps.json
  def index
    @sleeps = Sleep.all
  end

  # GET /sleeps/1
  # GET /sleeps/1.json
  def show
  end

  # GET /sleeps/new
  def new
    @sleep = Sleep.new
  end

  # GET /sleeps/1/edit
  def edit
  end

  # POST /sleeps
  # POST /sleeps.json
  def create
    @sleep = Sleep.new(sleep_params)

    respond_to do |format|
      if @sleep.save
        format.html { redirect_to @sleep, notice: 'Sleep was successfully created.' }
        format.json { render :show, status: :created, location: @sleep }
      else
        format.html { render :new }
        format.json { render json: @sleep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sleeps/1
  # PATCH/PUT /sleeps/1.json
  def update
    respond_to do |format|
      if @sleep.update(sleep_params)
        format.html { redirect_to @sleep, notice: 'Sleep was successfully updated.' }
        format.json { render :show, status: :ok, location: @sleep }
      else
        format.html { render :edit }
        format.json { render json: @sleep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sleeps/1
  # DELETE /sleeps/1.json
  def destroy
    @sleep.destroy
    respond_to do |format|
      format.html { redirect_to sleeps_url, notice: 'Sleep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sleep
      @sleep = Sleep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sleep_params
      params.require(:sleep).permit(:time, :user_id)
    end
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/views/sleeps/_form.html.erb
<%= form_for(@sleep) do |f| %>
  <% if @sleep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sleep.errors.count, "error") %> prohibited this sleep from being saved:</h2>

      <ul>
      <% @sleep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.date_select :time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sleeps/edit.html.erb
<h1>Editing Sleep</h1>

<%= render 'form' %>

<%= link_to 'Show', @sleep %> |
<%= link_to 'Back', sleeps_path %>

app/views/sleeps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sleeps</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sleeps.each do |sleep| %>
      <tr>
        <td><%= sleep.time %></td>
        <td><%= sleep.user %></td>
        <td><%= link_to 'Show', sleep %></td>
        <td><%= link_to 'Edit', edit_sleep_path(sleep) %></td>
        <td><%= link_to 'Destroy', sleep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sleep', new_sleep_path %>

app/views/sleeps/new.html.erb
<h1>New Sleep</h1>

<%= render 'form' %>

<%= link_to 'Back', sleeps_path %>

app/views/sleeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @sleep.time %>
</p>

<p>
  <strong>User:</strong>
  <%= @sleep.user %>
</p>

<%= link_to 'Edit', edit_sleep_path(@sleep) %> |
<%= link_to 'Back', sleeps_path %>