config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :sleeps
  resources :steps
  resources :med_coverages
  resources :prescriptions
  resources :visits
  resources :users

  get    '/login',  to: 'sessions#new',     as: 'new_login'
  post   '/login',  to: 'sessions#create',  as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  root 'homepage#index'

end

app/models/med_coverage.rb
class MedCoverage < ActiveRecord::Base
  belongs_to :user
end

app/controllers/med_coverages_controller.rb
class MedCoveragesController < ApplicationController
  before_action :set_med_coverage, only: [:show, :edit, :update, :destroy]

  # GET /med_coverages
  # GET /med_coverages.json
  def index
    @med_coverages = MedCoverage.all
  end

  # GET /med_coverages/1
  # GET /med_coverages/1.json
  def show
  end

  # GET /med_coverages/new
  def new
    @med_coverage = MedCoverage.new
  end

  # GET /med_coverages/1/edit
  def edit
  end

  # POST /med_coverages
  # POST /med_coverages.json
  def create
    @med_coverage = MedCoverage.new(med_coverage_params)

    respond_to do |format|
      if @med_coverage.save
        format.html { redirect_to @med_coverage, notice: 'Med coverage was successfully created.' }
        format.json { render :show, status: :created, location: @med_coverage }
      else
        format.html { render :new }
        format.json { render json: @med_coverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /med_coverages/1
  # PATCH/PUT /med_coverages/1.json
  def update
    respond_to do |format|
      if @med_coverage.update(med_coverage_params)
        format.html { redirect_to @med_coverage, notice: 'Med coverage was successfully updated.' }
        format.json { render :show, status: :ok, location: @med_coverage }
      else
        format.html { render :edit }
        format.json { render json: @med_coverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /med_coverages/1
  # DELETE /med_coverages/1.json
  def destroy
    @med_coverage.destroy
    respond_to do |format|
      format.html { redirect_to med_coverages_url, notice: 'Med coverage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_med_coverage
      @med_coverage = MedCoverage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def med_coverage_params
      params.require(:med_coverage).permit(:carrier, :plan_level, :plan_type, :network_type, :pcp_fee, :specialist_fee, :er_fee, :rx_brand_fee, :rx_generic_fee, :in_net_deduct_ind, :in_net_deduct_fam, :out_net_deduct_ind, :out_net_deduct_fam, :co_ins_percent, :out_of_pocket_max, :renewal_date)
    end
end

app/helpers/med_coverages_helper.rb
module MedCoveragesHelper
end

app/views/med_coverages/_form.html.erb
<%= form_for(@med_coverage) do |f| %>
  <% if @med_coverage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@med_coverage.errors.count, "error") %> prohibited this med_coverage from being saved:</h2>

      <ul>
      <% @med_coverage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :carrier %><br>
    <%= f.text_field :carrier %>
  </div>
  <div class="field">
    <%= f.label :plan_level %><br>
    <%= f.text_field :plan_level %>
  </div>
  <div class="field">
    <%= f.label :plan_type %><br>
    <%= f.text_field :plan_type %>
  </div>
  <div class="field">
    <%= f.label :network_type %><br>
    <%= f.text_field :network_type %>
  </div>
  <div class="field">
    <%= f.label :pcp_fee %><br>
    <%= f.number_field :pcp_fee %>
  </div>
  <div class="field">
    <%= f.label :specialist_fee %><br>
    <%= f.number_field :specialist_fee %>
  </div>
  <div class="field">
    <%= f.label :er_fee %><br>
    <%= f.number_field :er_fee %>
  </div>
  <div class="field">
    <%= f.label :rx_brand_fee %><br>
    <%= f.number_field :rx_brand_fee %>
  </div>
  <div class="field">
    <%= f.label :rx_generic_fee %><br>
    <%= f.number_field :rx_generic_fee %>
  </div>
  <div class="field">
    <%= f.label :in_net_deduct_ind %><br>
    <%= f.number_field :in_net_deduct_ind %>
  </div>
  <div class="field">
    <%= f.label :in_net_deduct_fam %><br>
    <%= f.number_field :in_net_deduct_fam %>
  </div>
  <div class="field">
    <%= f.label :out_net_deduct_ind %><br>
    <%= f.number_field :out_net_deduct_ind %>
  </div>
  <div class="field">
    <%= f.label :out_net_deduct_fam %><br>
    <%= f.number_field :out_net_deduct_fam %>
  </div>
  <div class="field">
    <%= f.label :co_ins_percent %><br>
    <%= f.number_field :co_ins_percent %>
  </div>
  <div class="field">
    <%= f.label :out_of_pocket_max %><br>
    <%= f.number_field :out_of_pocket_max %>
  </div>
  <div class="field">
    <%= f.label :renewal_date %><br>
    <%= f.date_select :renewal_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/med_coverages/edit.html.erb
<h1>Editing Med Coverage</h1>

<%= render 'form' %>

<%= link_to 'Show', @med_coverage %> |
<%= link_to 'Back', med_coverages_path %>

app/views/med_coverages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Med Coverages</h1>

<table>
  <thead>
    <tr>
      <th>Carrier</th>
      <th>Plan level</th>
      <th>Plan type</th>
      <th>Network type</th>
      <th>Pcp fee</th>
      <th>Specialist fee</th>
      <th>Er fee</th>
      <th>Rx brand fee</th>
      <th>Rx generic fee</th>
      <th>In net deduct ind</th>
      <th>In net deduct fam</th>
      <th>Out net deduct ind</th>
      <th>Out net deduct fam</th>
      <th>Co ins percent</th>
      <th>Out of pocket max</th>
      <th>Renewal date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @med_coverages.each do |med_coverage| %>
      <tr>
        <td><%= med_coverage.carrier %></td>
        <td><%= med_coverage.plan_level %></td>
        <td><%= med_coverage.plan_type %></td>
        <td><%= med_coverage.network_type %></td>
        <td><%= med_coverage.pcp_fee %></td>
        <td><%= med_coverage.specialist_fee %></td>
        <td><%= med_coverage.er_fee %></td>
        <td><%= med_coverage.rx_brand_fee %></td>
        <td><%= med_coverage.rx_generic_fee %></td>
        <td><%= med_coverage.in_net_deduct_ind %></td>
        <td><%= med_coverage.in_net_deduct_fam %></td>
        <td><%= med_coverage.out_net_deduct_ind %></td>
        <td><%= med_coverage.out_net_deduct_fam %></td>
        <td><%= med_coverage.co_ins_percent %></td>
        <td><%= med_coverage.out_of_pocket_max %></td>
        <td><%= med_coverage.renewal_date %></td>
        <td><%= link_to 'Show', med_coverage %></td>
        <td><%= link_to 'Edit', edit_med_coverage_path(med_coverage) %></td>
        <td><%= link_to 'Destroy', med_coverage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Med coverage', new_med_coverage_path %>

app/views/med_coverages/new.html.erb
<h1>New Med Coverage</h1>

<%= render 'form' %>

<%= link_to 'Back', med_coverages_path %>

app/views/med_coverages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Carrier:</strong>
  <%= @med_coverage.carrier %>
</p>

<p>
  <strong>Plan level:</strong>
  <%= @med_coverage.plan_level %>
</p>

<p>
  <strong>Plan type:</strong>
  <%= @med_coverage.plan_type %>
</p>

<p>
  <strong>Network type:</strong>
  <%= @med_coverage.network_type %>
</p>

<p>
  <strong>Pcp fee:</strong>
  <%= @med_coverage.pcp_fee %>
</p>

<p>
  <strong>Specialist fee:</strong>
  <%= @med_coverage.specialist_fee %>
</p>

<p>
  <strong>Er fee:</strong>
  <%= @med_coverage.er_fee %>
</p>

<p>
  <strong>Rx brand fee:</strong>
  <%= @med_coverage.rx_brand_fee %>
</p>

<p>
  <strong>Rx generic fee:</strong>
  <%= @med_coverage.rx_generic_fee %>
</p>

<p>
  <strong>In net deduct ind:</strong>
  <%= @med_coverage.in_net_deduct_ind %>
</p>

<p>
  <strong>In net deduct fam:</strong>
  <%= @med_coverage.in_net_deduct_fam %>
</p>

<p>
  <strong>Out net deduct ind:</strong>
  <%= @med_coverage.out_net_deduct_ind %>
</p>

<p>
  <strong>Out net deduct fam:</strong>
  <%= @med_coverage.out_net_deduct_fam %>
</p>

<p>
  <strong>Co ins percent:</strong>
  <%= @med_coverage.co_ins_percent %>
</p>

<p>
  <strong>Out of pocket max:</strong>
  <%= @med_coverage.out_of_pocket_max %>
</p>

<p>
  <strong>Renewal date:</strong>
  <%= @med_coverage.renewal_date %>
</p>

<%= link_to 'Edit', edit_med_coverage_path(@med_coverage) %> |
<%= link_to 'Back', med_coverages_path %>